title: CodeHarborHub
description: >- # A longer description
  CodeHarborHub is a platform for sharing and learning Web Development, Programming, and Software Development.
author: Ajay Dhangar
email: ajaydhangar49@gmail.com
baseurl: "/" # Leave empty for GitHub Pages
url: "https://codeharborhub.github.io" # Replace with your GitHub Pages URL

# Build settings
theme: minima # Choose a Jekyll theme (e.g., minima, cayman, slate, etc.)
plugins:
  - jekyll-feed # Enables RSS feed for posts

# Optional: Custom settings for the theme
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5 # Number of posts per page
