name: 📊 AI Dataset Submission
description: Submit a dataset for AI research, learning, or open-source use
title: "[Dataset]: Dataset Name"
labels:
  - ai
  - data
body:
  - type: markdown
    attributes:
      value: |
        ## 📊 AI Dataset Submission
        Contribute public datasets for open research and learning.
  - type: input
    id: dataset_name
    attributes:
      label: Dataset Name
      placeholder: e.g., Open AI Image Dataset
  - type: textarea
    id: description
    attributes:
      label: Dataset Description
      placeholder: Describe what the dataset contains and how it can be used.
  - type: input
    id: link
    attributes:
      label: Dataset Link
      placeholder: e.g., Kaggle / HuggingFace / GitHub URL
