name: 🤝 Collaboration Proposal
description: Suggest collaboration between CodeHarborHub and another organization/project
title: "[Collaboration]: Project Name"
labels:
  - partnership
  - open-source
assignees:
  - ajay-dhangar
body:
  - type: markdown
    attributes:
      value: |
        ## 🤝 Collaboration Proposal
        We love open-source partnerships! Submit your proposal here.
  - type: input
    id: org_name
    attributes:
      label: Organization / Project Name
      placeholder: e.g., TensorFlow India Community
    validations:
      required: true
  - type: input
    id: contact
    attributes:
      label: Contact Info
      placeholder: e.g., contact@organization.com
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Collaboration Idea
      placeholder: What kind of collaboration do you have in mind?
    validations:
      required: true
  - type: dropdown
    id: type
    attributes:
      label: Collaboration Type
      options:
        - Joint Event
        - Research Project
        - Mentorship / Internship
        - Technical Partnership
