name: 🎉 Community Event Proposal
description: Propose a meetup, workshop, or open-source event
title: "[Event]: Event Title"
labels:
  - community
  - event
assignees:
  - ajay-dhangar
body:
  - type: markdown
    attributes:
      value: |
        ## 🎉 Community Event Proposal
        Let's grow the AI & ML community together.
  - type: input
    id: event_name
    attributes:
      label: Event Name
      placeholder: e.g., CodeHarborHub Hack Night 2025
    validations:
      required: true
  - type: input
    id: date
    attributes:
      label: Proposed Date
      placeholder: e.g., Oct 25, 2025
  - type: textarea
    id: purpose
    attributes:
      label: Event Purpose
      placeholder: Why this event? Who benefits?
    validations:
      required: true
  - type: textarea
    id: agenda
    attributes:
      label: Agenda / Activities
      placeholder: |
        - Talk 1: AI & ML Trends
        - Workshop: TensorFlow Basics
    validations:
      required: true
  - type: input
    id: host
    attributes:
      label: Organizer / Host
      placeholder: e.g., Ajay Dhangar
