name: Contributor Onboarding
description: New contributors can introduce themselves and get started
title: "[Introduction]: Your Name"
labels:
  - contributor
  - onboarding
assignees:
  - ajay-dhangar
body:
  - type: markdown
    attributes:
      value: |
        ## Welcome to CodeHarborHub!

        Introduce yourself and share what you'd like to work on.
  - type: input
    id: name
    attributes:
      label: Name / Username
      placeholder: e.g., Ajay Dhangar / ajay-dhangar
  - type: dropdown
    id: interest
    attributes:
      label: Area of Interest
      options:
        - Frontend Development
        - Backend Development
        - AI / ML
        - Documentation
        - UI/UX Design
        - Community Management
        - Open Source
  - type: textarea
    id: goal
    attributes:
      label: What do you want to learn or contribute?
      placeholder: e.g., I want to contribute to AI tutorials or web development tools.
