name: 🎨 Design Submission
description: Submit a design for UI/UX, banners, or branding assets
title: "[Design]: Asset Name"
labels:
  - design
  - ui/ux
body:
  - type: markdown
    attributes:
      value: |
        ## 🎨 Design Submission — CodeHarborHub
        Submit your creative designs and get featured on our website!
  - type: input
    id: designer_name
    attributes:
      label: Designer Name
      placeholder: e.g., Ajay Dhangar
  - type: dropdown
    id: design_type
    attributes:
      label: Design Type
      options:
        - Logo
        - Website Banner
        - Event Poster
        - UI Mockup
        - Infographic
  - type: textarea
    id: description
    attributes:
      label: Design Description
      placeholder: Briefly explain your design and concept.
  - type: input
    id: design_link
    attributes:
      label: Design File / Link
      placeholder: e.g., Figma / Canva / Drive / Behance link
