name: Learning Resource Suggestion
description: Suggest tutorials, blogs, or open resources for our learners
title: "[Resource]: Resource Title"
labels:
  - education
  - learning
body:
  - type: markdown
    attributes:
      value: |
        ## 📘 Learning Resource Suggestion
        Suggest valuable AI, ML, or Web Development learning materials.
  - type: input
    id: title
    attributes:
      label: Resource Title
      placeholder: e.g., Intro to Neural Networks
  - type: input
    id: link
    attributes:
      label: Resource Link
      placeholder: e.g., https://towardsdatascience.com/...
  - type: dropdown
    id: type
    attributes:
      label: Resource Type
      options:
        - Article
        - Video
        - GitHub Repo
        - Course
        - Book
