name: 🧑‍🏫 Mentor Registration
description: Apply to mentor for AI & ML Summit 2025 or CodeHarborHub programs
title: "[Mentor]: Your Name"
labels:
  - mentor
  - community
assignees:
  - ajay-dhangar
body:
  - type: markdown
    attributes:
      value: |
        ## 🧑‍🏫 Mentor Registration — AI & ML Summit 2025

        Join as a **Mentor** to guide participants and speakers in our programs.
  - type: input
    id: name
    attributes:
      label: Full Name
      placeholder: e.g., Ajay Dhangar
    validations:
      required: true
  - type: input
    id: email
    attributes:
      label: Email Address
      placeholder: e.g., codeharborhub@gmail.com
    validations:
      required: true
  - type: dropdown
    id: domain
    attributes:
      label: Expertise Domain
      options:
        - Machine Learning
        - Deep Learning
        - Web Development
        - AI Tools / LLMs
        - Data Science
        - Cloud & DevOps
        - Open Source
    validations:
      required: true
  - type: textarea
    id: experience
    attributes:
      label: Experience Summary
      placeholder: Briefly describe your professional background (max 150 words)
    validations:
      required: true
  - type: input
    id: linkedin
    attributes:
      label: LinkedIn / Portfolio URL
      placeholder: e.g., https://linkedin.com/in/ajay-dhangar
