name: Project Idea Proposal
description: Suggest a new project or initiative for CodeHarborHub.
title: "[Idea]: Project Title"
labels:
  - idea
  - discussion
assignees:
  - ajay-dhangar
body:
  - type: markdown
    attributes:
      value: |
        ## CodeHarborHub — Project Idea Proposal

        Have a cool idea that fits CodeHarborHub’s mission of open-source tech education?  
        Share it here so the community can collaborate!

  - type: input
    id: project_name
    attributes:
      label: Project Name
      placeholder: e.g., AI Learning Portal or Open-Source Roadmaps
    validations:
      required: true

  - type: textarea
    id: idea_summary
    attributes:
      label: Idea Summary
      description: Briefly explain what the project is and why it matters.
      placeholder: e.g., A web platform that visualizes AI concepts interactively.
    validations:
      required: true

  - type: textarea
    id: goals
    attributes:
      label: Goals and Impact
      placeholder: e.g., To help learners practice machine learning interactively.
    validations:
      required: true

  - type: textarea
    id: potential_tech
    attributes:
      label: Potential Tech Stack
      placeholder: e.g., React, Node.js, MongoDB, TensorFlow.js
    validations:
      required: false

  - type: textarea
    id: contributors
    attributes:
      label: Contributors Needed
      description: What roles are needed? (e.g., frontend dev, designer, mentor)
      placeholder: e.g., 2 frontend devs, 1 mentor
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ---
        Once submitted, the community and maintainers will review and discuss your idea.
