name: ❓ Question / Help
description: Ask a question or get guidance
title: "[Question]: Topic"
labels:
  - question
  - help wanted
body:
  - type: markdown
    attributes:
      value: |
        ## ❓ Need Help or Have a Question?
        Ask here — our community will help!
  - type: textarea
    id: question
    attributes:
      label: Your Question
      placeholder: What do you need help with?
    validations:
      required: true
  - type: input
    id: topic
    attributes:
      label: Related Topic (Optional)
      placeholder: e.g., Machine Learning / React / Open Source
