name: 🎤 Register as Speaker
description: Apply to give a talk or workshop at the CodeHarborHub x Hacktoberfest 2025
title: "[Speaker]: Your Talk Title Here"
labels:
  - speaker
  - event
assignees:
  - ajay-dhangar
body:
  - type: markdown
    attributes:
      value: |
        ## 🎤 CodeHarborHub x Hacktoberfest 2025 — Speaker Registration

        Thank you for your interest in speaking at the **CodeHarborHub x Hacktoberfest 2025**!  
        Please fill out the following details carefully.  
        _After submission, our team will review your proposal and contact you._

  - type: input
    id: name
    attributes:
      label: Full Name
      description: Enter your full name as you would like it displayed.
      placeholder: e.g., Ajay Dhangar
    validations:
      required: true

  - type: input
    id: email
    attributes:
      label: Email Address
      description: For communication and confirmation.
      placeholder: e.g., codeharborhub@gmail.com 
    validations:
      required: true

  - type: input
    id: affiliation
    attributes:
      label: Organization / Affiliation
      description: Your company, university, or community name.
      placeholder: e.g., CodeHarborHub or Freelance Developer
    validations:
      required: false

  - type: input
    id: talk_title
    attributes:
      label: Talk / Workshop Title
      description: The title of your session.
      placeholder: e.g., "Building Smarter AI Agents with Open-Source Tools"
    validations:
      required: true

  - type: textarea
    id: abstract
    attributes:
      label: Talk Abstract / Description
      description: A short summary of your talk (100–250 words).
      placeholder: |
        Describe your session overview, key takeaways, and audience benefits.
    validations:
      required: true

  - type: dropdown
    id: format
    attributes:
      label: Session Type
      description: Select the format that best fits your proposal.
      options:
        - Keynote Talk (30–45 min)
        - Workshop (1–2 hrs)
        - Lightning Talk (10–15 min)
        - Panel Discussion
    validations:
      required: true

  - type: dropdown
    id: experience
    attributes:
      label: Experience Level of Audience
      description: Who is this talk best suited for?
      options:
        - Beginner
        - Intermediate
        - Advanced
        - All Levels
    validations:
      required: true

  - type: input
    id: preferred_date
    attributes:
      label: Preferred Presentation Date
      description: Suggest your preferred date (if known).
      placeholder: e.g., Oct 25, 2025
    validations:
      required: false

  - type: textarea
    id: bio
    attributes:
      label: Speaker Bio
      description: Write a short professional bio (max 100 words).
      placeholder: |
        Example: Ajay Dhangar is a MERN Stack Developer and Founder of CodeHarborHub, passionate about open-source and AI education.
    validations:
      required: true

  - type: input
    id: social_links
    attributes:
      label: Social / Portfolio Links
      description: Add relevant profiles (GitHub, LinkedIn, website, etc.)
      placeholder: e.g., https://github.com/ajay-dhangar
    validations:
      required: false

  - type: textarea
    id: additional_notes
    attributes:
      label: Additional Notes
      description: Anything else we should know?
      placeholder: Special requirements, collaboration interests, or timing notes.
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ---
        Once submitted, our review team will reach out within **7–10 days**.  
        For queries, please contact [CodeHarborHub Team](https://github.com/CodeHarborHub).
