name: 🎬 Video Content Proposal
description: Suggest or contribute video content for CodeHarborHub YouTube / Tutorials
title: "[Video]: Topic Name"
labels:
  - video
  - content
body:
  - type: markdown
    attributes:
      value: |
        ## 🎬 Video Content Proposal
        Contribute tutorials, interviews, or educational videos for CodeHarborHub.
  - type: input
    id: creator
    attributes:
      label: Creator / Presenter
      placeholder: e.g., Ajay Dhangar
  - type: input
    id: topic
    attributes:
      label: Video Topic
      placeholder: e.g., Getting Started with Generative AI
  - type: dropdown
    id: format
    attributes:
      label: Video Type
      options:
        - Tutorial
        - Interview
        - Event Recording
        - Announcement
        - Course Lecture
  - type: textarea
    id: summary
    attributes:
      label: Description
      placeholder: Short description of video content
